CREATE TABLE IF NOT EXISTS university_admissions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 university_id BIGINT UNSIGNED NOT NULL UNIQUE,
 titulo VARCHAR(190) NOT NULL,
 descripcion_general TEXT NOT NULL,
 orden INT UNSIGNED NOT NULL DEFAULT 0,
 activo TINYINT(1) NOT NULL DEFAULT 1,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (university_id) REFERENCES universities(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS admission_steps (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 admission_id BIGINT UNSIGNED NOT NULL,
 titulo VARCHAR(190) NOT NULL,
 descripcion TEXT NOT NULL,
 fecha DATE NULL,
 imagen VARCHAR(255) NULL,
 boton_texto VARCHAR(190) NULL,
 boton_url VARCHAR(500) NULL,
 orden INT UNSIGNED NOT NULL DEFAULT 0,
 activo TINYINT(1) NOT NULL DEFAULT 1,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX admission_steps_order (admission_id,activo,orden,id),
 FOREIGN KEY (admission_id) REFERENCES university_admissions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
