CREATE TABLE IF NOT EXISTS university_exams (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 university_id BIGINT UNSIGNED NOT NULL UNIQUE,
 titulo VARCHAR(190) NOT NULL,
 descripcion_general TEXT NOT NULL,
 duracion VARCHAR(100) NULL,
 cantidad_preguntas INT UNSIGNED NULL,
 activo TINYINT(1) NOT NULL DEFAULT 1,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (university_id) REFERENCES universities(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS exam_categories (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 exam_id BIGINT UNSIGNED NOT NULL,
 nombre VARCHAR(190) NOT NULL,
 descripcion TEXT NOT NULL,
 cantidad_preguntas INT UNSIGNED NULL,
 imagen VARCHAR(255) NULL,
 orden INT UNSIGNED NOT NULL DEFAULT 0,
 activo TINYINT(1) NOT NULL DEFAULT 1,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX exam_category_order (exam_id,activo,orden,id),
 FOREIGN KEY (exam_id) REFERENCES university_exams(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
