CREATE TABLE IF NOT EXISTS siov_areas (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, codigo VARCHAR(16) NOT NULL UNIQUE,
 nombre VARCHAR(255) NOT NULL, color VARCHAR(7) NOT NULL, descripcion TEXT NOT NULL,
 orden INT UNSIGNED NOT NULL DEFAULT 0, activo TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS siov_questions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, area_id BIGINT UNSIGNED NOT NULL,
 texto TEXT NOT NULL, orden INT UNSIGNED NOT NULL DEFAULT 0, activo TINYINT(1) NOT NULL DEFAULT 1,
 FOREIGN KEY(area_id) REFERENCES siov_areas(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS siov_careers (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, area_id BIGINT UNSIGNED NOT NULL,
 nombre VARCHAR(255) NOT NULL, relacionada TINYINT(1) NOT NULL DEFAULT 1,
 orden INT UNSIGNED NOT NULL DEFAULT 0, activo TINYINT(1) NOT NULL DEFAULT 1,
 FOREIGN KEY(area_id) REFERENCES siov_areas(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS siov_universities (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, codigo VARCHAR(16) NOT NULL UNIQUE,
 nombre VARCHAR(255) NOT NULL, url VARCHAR(500) NOT NULL, tipoPrueba VARCHAR(255) NOT NULL,
 orden INT UNSIGNED NOT NULL DEFAULT 0, activo TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS siov_career_universities (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, career_id BIGINT UNSIGNED NOT NULL,
 university_id BIGINT UNSIGNED NOT NULL, facultad VARCHAR(255) NOT NULL,
 titulo VARCHAR(255) NOT NULL, duracion VARCHAR(255) NOT NULL,
 modalidad VARCHAR(255) NOT NULL, campoLaboral TEXT NOT NULL,
 orden INT UNSIGNED NOT NULL DEFAULT 0, activo TINYINT(1) NOT NULL DEFAULT 1,
 FOREIGN KEY(career_id) REFERENCES siov_careers(id),
 FOREIGN KEY(university_id) REFERENCES siov_universities(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- Solo acumuladores globales. Sin filas por visitante, fechas de eventos, cookies ni respuestas.
CREATE TABLE IF NOT EXISTS siov_metrics (
 evento VARCHAR(32) NOT NULL, dimension_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
 cantidad BIGINT UNSIGNED NOT NULL DEFAULT 0, minutos_totales BIGINT UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY(evento,dimension_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
