CREATE TABLE IF NOT EXISTS universities (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 nombre VARCHAR(190) NOT NULL,
 slug VARCHAR(190) NOT NULL UNIQUE,
 logo VARCHAR(255) NULL,
 descripcion TEXT NOT NULL,
 imagen_portada VARCHAR(255) NULL,
 orden INT UNSIGNED NOT NULL DEFAULT 0,
 activo TINYINT(1) NOT NULL DEFAULT 1,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX universities_visible_order (activo,orden,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
